#!/bin/bash
###############################################################################################################
#   Filename: i3/background                                                                                   #
# Maintainer: Yash Srivastav <yashsriv01@gmail.com>                                                           #
#        URL: http://github.com/yashsriv/dotfiles                                                             #
#                                                                                                             #
# Sets Background for i3 session                                                                              #
###############################################################################################################

#files=(~/XKCD/images/*)
#COMIC=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
#DISPLAY=:0 feh --bg-center $COMIC
#echo $COMIC > ~/.current_comic
files=(/media/yash/Extra/Facets/*)
IMAGE=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
DISPLAY=:0 feh --bg-fill $IMAGE
