#!/bin/bash
###############################################################################################################
#   Filename: i3/background                                                                                   #
# Maintainer: Yash Srivastav <yashsriv01@gmail.com>                                                           #
#        URL: http://github.com/yashsriv/dotfiles                                                             #
#                                                                                                             #
# Sets Background for i3 session                                                                              #
###############################################################################################################

# XKCD
#files=(~/XKCD/images/*)
#COMIC=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
#DISPLAY=:0 feh --bg-center $COMIC
#echo $COMIC > ~/.current_comic


# Minimalist
if [ -f /etc/arch-release ]; then
  DISPLAY=:0 feh --bg-fill ~/Documents/arch.png
elif [ -f /etc/debian_version ]; then
  DISPLAY=:0 feh --bg-fill ~/Documents/debian.png
else
  # Facets
  files=(/media/yash/Extra/Facets/*)
  IMAGE=$(printf "%s\n" "${files[RANDOM % ${#files[@]}]}")
  DISPLAY=:0 feh --bg-fill $IMAGE
fi
